In this assignment the goal is to implement the dimensionality reduction technique *Principal Component Analysis (PCA)* to a very high dimensional data and apply visualization. Note that you are not allowed to use the built-in PCA API provided by the sklearn library. Instead you will be implementing from the scratch.

    For this task we use the MNIST dataset. First we download the dataset using openml api

In [48]:
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784', cache=False)
X = mnist.data
y = mnist.target
print(X.shape, y.shape)

(70000, 784) (70000,)


# Part-1: Preprocessing
Before implementing PCA you are required to perform some preprocessing steps:
1. Mean normalization: Replace each feature/attribute, $x_{ji}$ with $x_j - \mu_j$, In other words, determine the mean of each feature set, and then for each feature subtract the mean from the value, so we re-scale the mean to be 0 
2. Feature scaling: If features have very different scales then scale make them comparable by altering the scale, so they all have a comparable range of values e.g. $x_{ji}$ is set to $(x_j - \mu_j) / s_j$  Where $s_j$ is some measure of the range, so could be  $\max(x_j) - \min(x_j)$ or Standard deviation $stddev(x_j)$.

In [57]:
#TODO Implement mean normalization and feature scaling


import numpy as np
#transpose X:
Xt = np.transpose(X)
# Average of the values in each row of X
ave_rows = np.mean(Xt, axis=0)

# Standard Deviation of the values in each row of X
std_rows = Xt.std(axis=0)    

#should be same number of rows as in X.shape:
# Print the shape of ave_rows
print(ave_rows.shape)
# Print the shape of std_rows
print(std_rows.shape)

#Mean normalization of X
X_norm = (Xt - ave_cols)

#Feature Scaling of X
X_scaled = X_norm/std_cols

print(X_norm)
print(X_scaled)

(70000,)
(70000,)
[[-35.10841837 -39.6619898  -24.7997449  ... -37.28443878 -33.87627551
  -53.35841837]
 [-35.10841837 -39.6619898  -24.7997449  ... -37.28443878 -33.87627551
  -53.35841837]
 [-35.10841837 -39.6619898  -24.7997449  ... -37.28443878 -33.87627551
  -53.35841837]
 ...
 [-35.10841837 -39.6619898  -24.7997449  ... -37.28443878 -33.87627551
  -53.35841837]
 [-35.10841837 -39.6619898  -24.7997449  ... -37.28443878 -33.87627551
  -53.35841837]
 [-35.10841837 -39.6619898  -24.7997449  ... -37.28443878 -33.87627551
  -53.35841837]]
[[-0.44079014 -0.47280168 -0.37816163 ... -0.44463709 -0.42776375
  -0.5574036 ]
 [-0.44079014 -0.47280168 -0.37816163 ... -0.44463709 -0.42776375
  -0.5574036 ]
 [-0.44079014 -0.47280168 -0.37816163 ... -0.44463709 -0.42776375
  -0.5574036 ]
 ...
 [-0.44079014 -0.47280168 -0.37816163 ... -0.44463709 -0.42776375
  -0.5574036 ]
 [-0.44079014 -0.47280168 -0.37816163 ... -0.44463709 -0.42776375
  -0.5574036 ]
 [-0.44079014 -0.47280168 -0.37816163 ... -0

# Part-2: Covariance matrix
Now the preprocessing is finished. Next, as explained in the lecture, you need to compute the covariance matrix https://en.wikipedia.org/wiki/Covariance_matrix. Given $n \times m$ $n$ rows and $m$ columns matrix, a covariance matrix is an $n \times n$ matrix given as below (sigma)
$\Sigma = \frac{1}{m}\sum{\left(x^{i}\right)\times \left(x^{i}\right)^{T}}$
You may use the "numpy.cov" function in numpy library 

In [64]:
#TODO Compute X to covariance matrix cov_matrix.
cov_matrix = np.cov(X_scaled)
print(cov_matrix)

[[0.00590748 0.00590748 0.00590748 ... 0.00590748 0.00590748 0.00590748]
 [0.00590748 0.00590748 0.00590748 ... 0.00590748 0.00590748 0.00590748]
 [0.00590748 0.00590748 0.00590748 ... 0.00590748 0.00590748 0.00590748]
 ...
 [0.00590748 0.00590748 0.00590748 ... 0.00590748 0.00590748 0.00590748]
 [0.00590748 0.00590748 0.00590748 ... 0.00590748 0.00590748 0.00590748]
 [0.00590748 0.00590748 0.00590748 ... 0.00590748 0.00590748 0.00590748]]


# Part-3: SVD computation
Now compute the SVD on the covariance matrix $SVD(\Sigma)$. You may use the svd implementation in numpy.linalg.svd

In [72]:
import numpy as np
def getSVD(temp):
    U, S, V = np.linalg.svd(temp,  full_matrices=False)
    return (U,S,V)
U,S,V = getSVD(cov_matrix) #SVD

[[-0.00574346 -0.00406003 -0.00156353 ...  0.18398401 -0.43351197
   0.21373349]
 [-0.00574346 -0.00406003 -0.00156353 ... -0.15768476  0.01236295
   0.15352689]
 [-0.00574346 -0.00406003 -0.00156353 ...  0.01426123 -0.18272744
  -0.27354152]
 ...
 [-0.00574346 -0.00406003 -0.00156353 ...  0.00255002 -0.01247046
  -0.03903776]
 [-0.00574346 -0.00406003 -0.00156353 ...  0.00255002 -0.01247046
  -0.03903776]
 [-0.00574346 -0.00406003 -0.00156353 ...  0.00255002 -0.01247046
  -0.03903776]]


# Part-4: Compute PCA matrix (K dimensional)
Now select the first $k$ columns from the matrix $U$ and multiply with the 

In [ ]:
def getKComponents(U, X, K):
    #TODO implement matrix multiplication of first k columns of U * X
    Uk = np.transpose(U[:,:K])
    out = np.matmul(Uk,X)
    return (out)
#I set variable K to 30 for testing:
PCA = getKComponents(U,X_scaled,30)

#mean_rows = np.mean(PCA, axis=0)

    # Standard Deviation of the values in each row of U
#std_PCA_rows = PCA.std(axis=0)   
#Xapprox = (PCA-mean_rows)/std_PCA_rows
#print(Xapprox)
#print(X.shape[0])

#m = 0
#sumCtr = 0
#for i in range(X_scaled[:30,:].shape[0]):
#    for j in range(X_scaled[:30,:].shape[1]):
#        sumCtr = sumCtr + abs(X_scaled[i,j]**j-Xapprox**j)**2
#        m = m+1
#sumCtr = sumCtr/m

#m = 0
#sumDen = 0
#for i in range(X_scaled[:30,:].shape[0]):
#    for j in range(X_scaled[:30,:].shape[1]):
#        sumDen = sumDen + abs(X_scaled[i,j]**j)**2
#        m = m+1
#sumDen = sumDen/m

#recErr = sumCtr/sumDen
 
#print(recErr)

[[-0.59305587  1.00329355  2.25065173 ... -0.44940616 -1.40721551
   1.17535297]
 [ 0.10462511  1.32628427 -0.35456838 ... -2.51856169 -0.71230292
   1.10127436]
 [-0.89183062  1.30367771  0.53647554 ...  0.76123173  1.39925584
   1.98449917]
 ...
 [-0.66310327 -0.93858969  0.17883476 ... -1.17276335 -0.47698188
  -1.57966912]
 [ 0.45425095  0.73788346  0.012686   ...  0.1178245   1.2265923
   0.54927186]
 [-1.5679233  -1.74273966 -1.49305582 ... -1.32327914 -1.53879954
  -0.88370852]]
70000


C:\Users\henri\Anaconda3\lib\site-packages\ipykernel_launcher.py:21: RuntimeWarning: overflow encountered in square
C:\Users\henri\Anaconda3\lib\site-packages\ipykernel_launcher.py:21: RuntimeWarning: overflow encountered in add
C:\Users\henri\Anaconda3\lib\site-packages\ipykernel_launcher.py:21: RuntimeWarning: overflow encountered in power


# Part-5: Compute Reconstruction Error
Implement a function to compute the variance ratio (from reconstruction error)

In [93]:
def getVarianceRatio(PCA, K, X):
    #Implement computation of reconstruction error
    # Average of the values in each row of U
    mean_rows = np.mean(PCA, axis=0)

    # Standard Deviation of the values in each row of U
    std_PCA_rows = PCA.std(axis=0)   
    Xapprox = (PCA-mean_rows)/std_PCA_rows
    print(Xapprox)
    #i=
    recErr = (1/30*sum(abs(X[:30,:]**i-Xapprox**i)**2))/(1/30*sum(abs(X[:30,:]**i)**2))
    return (recErr)

getVarianceRatio(PCA,30,X_scaled)
print(recErr)

    #Xapprox = Uk.Z
    #ratio = (1/m sgm[i=1,m]||x^i-xapprox^i||^2)/(1/m sgm[i=1,m]||x^i||^2)

SyntaxError: invalid syntax (<ipython-input-93-66e02b13050e>, line 11)

# Part-6: Scatter plot 2-dimensional PCA
Using matplotlib plot the 2-dimensional scatter plot of the first 2 compoenents with y (target) as labels

In [ ]:
#TODO Plot the scatter plot

Find the minimum value of $K$ with which the ratio between averaged squared projection error with total variation in data is less than 10% in other words we retain 90% of the variance. You can achieve this by repeating getKComponents with $K=1$ until the variance ratio is <= 10%.

# Part-7: TSNE visualization
Finally, having found an optimal $K$ use these components as an input data to another dimensionality reduction method called tSNE (https://en.wikipedia.org/wiki/T-distributed_stochastic_neighbor_embedding) and reduce it to 2 dimensions.

In [ ]:
from sklearn.manifold import TSNE
rndperm = np.random.permutation(mnist.data.shape[0])
n_sne = 10000 #it is sufficient if done for 10k samples
tsne = TSNE(n_components=2, verbose=1, perplexity=40, n_iter=300)
tsne_pca_results = tsne.fit_transform(pca_result_50[rndperm[:n_sne]])

Finally, scatter plot the components given by the tSNE using matplotlib compare it to the earlier scatter plot.

In [ ]:
#TODO: Scatter plot the 2-dimensional tsne compoents with target as labels